name = "tttn"
compatibility_date = "2026-05-01"
main = "worker.js"

# 只托管需要的文件，排除 .git 和其他大文件/缓存
assets = { 
  directory = "./",
  exclude = [
    ".git/**",
    ".wrangler/**",
    "node_modules/**",
    "*.log",
    ".github/**"
  ]
}
